[tool.poetry]
name = "ic"
version = "0.1.0"
description = ""
authors = ["SpackiGabriel <ifprgabriel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
